# Generated by Django 3.2.7 on 2023-05-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.area'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hour_end',
            field=models.TimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hour_start',
            field=models.TimeField(verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(max_length=45, verbose_name='course name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon'), ('night', 'night')], max_length=45, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_course_id',
            field=models.CharField(max_length=20, verbose_name='registration course id'),
        ),
    ]
