# Generated by Django 4.1.7 on 2023-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='acronym',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(max_length=90, verbose_name='course name'),
        ),
    ]
