# Generated by Django 4.1.7 on 2023-05-23 06:29

import common.validator.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20230522_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name_course',
            field=models.CharField(max_length=45, validators=[common.validator.validator.validate_uppercase], verbose_name='course name'),
        ),
    ]
