# Generated by Django 4.1.7 on 2023-05-24 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_remove_area_block_area_blocks'),
        ('course', '0002_auto_20230522_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.block'),
        ),
    ]
