# Generated by Django 4.1.7 on 2023-05-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_block'),
        ('course', '0005_alter_course_registration_course_id'),
    ]

    operations = [
    ]
