# Generated by Django 4.1.7 on 2023-05-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_merge_20230527_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
