# Generated by Django 4.1.7 on 2023-05-28 01:31

import common.validator.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='acronym',
            field=models.CharField(max_length=3, null=True, validators=[common.validator.validator.validate_uppercase, common.validator.validator.validate_acronym_length], verbose_name='acronym'),
        ),
    ]
