# Generated by Django 4.1.7 on 2023-05-28 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_acronym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='hour_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hour_start',
        ),
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
    ]
