# Generated by Django 4.1.7 on 2023-05-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_course_hour_end_remove_course_hour_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
