# Generated by Django 4.1.7 on 2023-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_id_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id_course',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
