# Generated by Django 4.1.7 on 2023-06-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, verbose_name='professor'),
        ),
    ]
