# Generated by Django 3.2.7 on 2023-05-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='id_history',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id history'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id_job',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id job'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='id_proficiency',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id proficiency'),
        ),
    ]
