# Generated by Django 4.1.7 on 2023-06-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name_job',
            field=models.CharField(max_length=160, verbose_name='name job'),
        ),
    ]
