# Generated by Django 4.1.7 on 2023-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
    ]
