# Generated by Django 4.1.7 on 2023-06-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='blocks',
        ),
    ]
