# Generated by Django 4.1.7 on 2023-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('user', '0002_alter_history_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='academic_degrees',
            field=models.ManyToManyField(blank=True, null=True, to='user.academicdegree'),
        ),
        migrations.AlterField(
            model_name='history',
            name='blocks',
            field=models.ManyToManyField(blank=True, null=True, related_name='history_blocks', to='area.block'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_area',
            field=models.DateField(null=True, verbose_name='date area'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_campus',
            field=models.DateField(null=True, verbose_name='date campus'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_career',
            field=models.DateField(null=True, verbose_name='date career'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_institute',
            field=models.DateField(null=True, verbose_name='date institute'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_professor',
            field=models.DateField(null=True, verbose_name='date professor'),
        ),
    ]
