# Generated by Django 4.1.7 on 2023-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_academicdegree_name_alter_job_name_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_phone',
            field=models.CharField(max_length=14, verbose_name='cell phone'),
        ),
    ]
