# Generated by Django 4.1.7 on 2023-05-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_rename_name_block_name_block_remove_block_id_and_more'),
        ('user', '0010_alter_user_history_alter_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.block'),
        ),
    ]
