# Generated by Django 4.2.1 on 2023-05-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_remove_block_area_area_block'),
        ('user', '0013_alter_user_block_alter_user_history_alter_user_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block',
        ),
        migrations.AddField(
            model_name='user',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='area.block'),
        ),
    ]
