# Generated by Django 4.1.7 on 2023-05-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_user_block_user_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='history',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.history', unique=True),
        ),
    ]
