# Generated by Django 4.1.7 on 2023-05-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_history_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='nome',
            new_name='name',
        ),
    ]
