# Generated by Django 4.1.7 on 2023-05-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_nome_history_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
    ]
