# Generated by Django 4.2.1 on 2023-05-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_alter_area_blocks'),
        ('user', '0019_remove_history_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='users', to='area.block'),
        ),
    ]
