# Generated by Django 4.2.1 on 2023-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_alter_area_blocks'),
        ('user', '0020_alter_user_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id_academic_degree', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('punctuation', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='history_blocks', to='area.block'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='user_blocks', to='area.block'),
        ),
        migrations.AddField(
            model_name='history',
            name='academic_degrees',
            field=models.ManyToManyField(blank=True, to='user.academicdegree'),
        ),
    ]
