# Generated by Django 4.2.1 on 2023-05-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_academicdegree_history_blocks_alter_user_blocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='academic_degrees',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_degrees',
            field=models.ManyToManyField(blank=True, to='user.academicdegree'),
        ),
    ]
