# Generated by Django 4.2.6 on 2023-11-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_class_id', models.CharField(max_length=20, unique=True, verbose_name='registration class id')),
                ('period', models.CharField(choices=[('morning', 'MORNING'), ('afternoon', 'AFTERNOON'), ('night', 'NIGHT')], max_length=45, verbose_name='period')),
                ('semester', models.IntegerField(verbose_name='semester')),
                ('students', models.IntegerField(max_length=25, verbose_name='students')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
            options={
                'verbose_name': 'classs',
                'verbose_name_plural': 'classes',
            },
        ),
    ]
