# Generated by Django 4.2.6 on 2023-11-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classs',
            name='students',
            field=models.IntegerField(default=0, verbose_name='students'),
        ),
    ]
