<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-09-05 04:12
=======
# Generated by Django 4.1.7 on 2023-09-05 03:31
>>>>>>> be2cf6c0dc9a102553293d6f6138b0e5eed3b659

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('area', '0001_initial'),
        ('attribution_preference', '0001_initial'),
        ('timetable', '0001_initial'),
=======
        ('timetable', '0001_initial'),
        ('attribution_preference', '0001_initial'),
        ('area', '0001_initial'),
>>>>>>> be2cf6c0dc9a102553293d6f6138b0e5eed3b659
    ]

    operations = [
        migrations.AddField(
            model_name='preference_schedule',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot'),
        ),
        migrations.AddField(
            model_name='course_preference',
            name='attribution_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribution_preference.attribution_preference'),
        ),
        migrations.AddField(
            model_name='course_preference',
            name='blockk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.blockk'),
        ),
        migrations.AddField(
            model_name='course_preference',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
    ]
