<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-11-02 00:24
=======
# Generated by Django 4.1.7 on 2023-11-03 20:04
>>>>>>> 53be2f9e1a979e486cab79cf2e26ce32a738464b

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('area', '0001_initial'),
<<<<<<< HEAD
=======
        ('timetable', '0001_initial'),
>>>>>>> 53be2f9e1a979e486cab79cf2e26ce32a738464b
        ('attribution_preference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference_schedule',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timeslot'),
        ),
        migrations.AddField(
            model_name='course_preference',
            name='attribution_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribution_preference.attribution_preference'),
        ),
        migrations.AddField(
            model_name='course_preference',
            name='blockk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.blockk'),
        ),
        migrations.AddField(
            model_name='course_preference',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
    ]
