# Generated by Django 4.1.7 on 2023-05-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_preference', '0002_auto_20230522_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribution_preference',
            options={'verbose_name': 'attribution_preference', 'verbose_name_plural': 'attribution_preferences'},
        ),
        migrations.AlterModelOptions(
            name='attribution_preference_course_preference',
            options={'verbose_name': 'attribution_preference_course_preference', 'verbose_name_plural': 'attribution_preference_course_preferences'},
        ),
        migrations.AlterModelOptions(
            name='attribution_workload_supplementation',
            options={'verbose_name': 'attribution_workload_supplementation', 'verbose_name_plural': 'attribution_workload_supplementations'},
        ),
        migrations.AlterModelOptions(
            name='course_preference',
            options={'verbose_name': 'course_preference', 'verbose_name_plural': 'course_preferences'},
        ),
        migrations.AlterModelOptions(
            name='preference_schedule',
            options={'verbose_name': 'preference_schedule', 'verbose_name_plural': 'preference_schedules'},
        ),
        migrations.AlterModelOptions(
            name='teaching_support_activity',
            options={'verbose_name': 'teaching_support_activity', 'verbose_name_plural': 'teaching_support_activities'},
        ),
        migrations.AlterModelOptions(
            name='teaching_support_activity_attribution',
            options={'verbose_name': 'teaching_support_activity_attribution', 'verbose_name_plural': 'teaching_support_activity_attributions'},
        ),
        migrations.AlterModelOptions(
            name='workload_supplementation',
            options={'verbose_name': 'workload_supplementation', 'verbose_name_plural': 'workload_supplementations'},
        ),
    ]
