# Generated by Django 4.1.7 on 2023-05-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_preference', '0003_alter_attribution_preference_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution_workload_supplementation',
            name='attribution_preference',
        ),
        migrations.RemoveField(
            model_name='attribution_workload_supplementation',
            name='workload_supplementation',
        ),
        migrations.DeleteModel(
            name='Teaching_support_activity',
        ),
        migrations.RemoveField(
            model_name='teaching_support_activity_attribution',
            name='attribution_preference',
        ),
        migrations.DeleteModel(
            name='Attribution_workload_supplementation',
        ),
        migrations.DeleteModel(
            name='Teaching_support_activity_attribution',
        ),
        migrations.DeleteModel(
            name='Workload_supplementation',
        ),
    ]
