# Generated by Django 4.1.7 on 2023-06-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
        ('attribution_preference', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_preference',
            name='count_course',
        ),
        migrations.RemoveField(
            model_name='course_preference',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course_preference',
            name='period',
        ),
        migrations.RemoveField(
            model_name='course_preference',
            name='priority',
        ),
        migrations.AddField(
            model_name='course_preference',
            name='attribution_preference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attribution_preference.attribution_preference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_preference',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
            preserve_default=False,
        ),
    ]
