# Generated by Django 4.1.7 on 2023-05-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_preference', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_preference',
            name='period',
            field=models.CharField(choices=[('morning', 'MORNING'), ('afternoon', 'AFTERNOON'), ('night', 'NIGHT')], max_length=45, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='course_preference',
            name='priority',
            field=models.CharField(choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY')], max_length=45, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='preference_schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], max_length=45, verbose_name='day'),
        ),
    ]
