# Generated by Django 4.1.7 on 2023-08-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_preference', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_preference',
            name='priority',
            field=models.CharField(choices=[('primary', 'PRIMARY'), ('secondary', 'SECONDARY')], default=1, max_length=45, verbose_name='priority'),
            preserve_default=False,
        ),
    ]
