# Generated by Django 4.1.7 on 2023-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution_preference', '0004_remove_attribution_workload_supplementation_attribution_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_preference',
            name='priority',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], max_length=45, verbose_name='priority'),
        ),
    ]
