# Generated by Django 4.1.7 on 2023-04-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professors",
            name="avatar",
        ),
        migrations.AddField(
            model_name="professors",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff status"),
        ),
        migrations.AlterField(
            model_name="professors",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="professors",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="professors",
            name="promtuary",
            field=models.CharField(max_length=9, unique=True, verbose_name="promtuary"),
        ),
    ]
