# Generated by Django 4.1.7 on 2023-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_course_end_time_remove_course_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="course",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Mon", "Monday"),
                    ("Tue", "Tuesday"),
                    ("Wed", "Wednesday"),
                    ("Thu", "Thursday"),
                    ("Fri", "Friday"),
                    ("Sat", "Saturday"),
                    ("Sun", "Sunday"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
