# Generated by Django 4.1.7 on 2023-04-08 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_course_end_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="instructor",
            new_name="teacher",
        ),
    ]
