# Generated by Django 3.2.7 on 2023-05-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=45, verbose_name='name area')),
                ('registration_area_id', models.CharField(max_length=20, verbose_name='registration area id')),
                ('exchange_area', models.BooleanField(default=True, verbose_name='exchange area')),
            ],
        ),
    ]
