# Generated by Django 4.1.7 on 2023-05-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('registration_block_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_block', models.CharField(max_length=90, verbose_name='name block')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_area', models.CharField(max_length=45, unique=True, verbose_name='name area')),
                ('registration_area_id', models.CharField(max_length=20, unique=True, verbose_name='registration area id')),
                ('exchange_area', models.BooleanField(default=True, verbose_name='exchange area')),
                ('is_high_school', models.BooleanField(default=True, verbose_name='is high school')),
                ('blocks', models.ManyToManyField(to='area.block')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
    ]
