# Generated by Django 4.2.1 on 2023-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='areas', to='area.block'),
        ),
    ]
