# Generated by Django 4.1.7 on 2023-05-23 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_block_id', models.CharField(max_length=20, verbose_name='registration block id')),
                ('name', models.CharField(max_length=45, verbose_name='name block')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
        ),
    ]
