# Generated by Django 4.1.7 on 2023-05-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='registration_block_id',
            field=models.CharField(max_length=20, verbose_name='registration block id'),
        ),
    ]
