# Generated by Django 4.1.7 on 2023-05-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='name',
            new_name='name_block',
        ),
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AlterField(
            model_name='block',
            name='registration_block_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
