# Generated by Django 4.1.7 on 2023-05-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_alter_block_registration_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='registration_block_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='registration block id'),
        ),
    ]
