# Generated by Django 4.2.1 on 2023-05-23 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_rename_name_block_name_block_remove_block_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='area.block'),
        ),
    ]
