# Generated by Django 4.1.7 on 2023-05-28 04:52

import common.validator.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_alter_block_id_alter_block_registration_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='acronym',
            field=models.CharField(max_length=3, validators=[common.validator.validator.validate_uppercase, common.validator.validator.validate_acronym_length], verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name_block',
            field=models.CharField(max_length=90, unique=True, verbose_name='name block'),
        ),
    ]
