# Generated by Django 4.2.1 on 2023-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_remove_block_area_area_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='block',
        ),
        migrations.AddField(
            model_name='area',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='area.block'),
        ),
    ]
