# Generated by Django 4.1.7 on 2023-05-28 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_remove_area_block_area_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'area', 'verbose_name_plural': 'areas'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'block', 'verbose_name_plural': 'blocks'},
        ),
    ]
