# Generated by Django 4.1.7 on 2023-05-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_area_is_high_school'),
        ('area', '0005_remove_area_block_area_blocks'),
    ]

    operations = [
    ]
