# Generated by Django 4.2.1 on 2023-05-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_remove_area_block_area_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='areas', to='area.block'),
        ),
    ]
