# Generated by Django 4.1.7 on 2023-05-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_alter_area_options_alter_block_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='blocks',
            field=models.ManyToManyField(blank=True, editable=False, to='area.block'),
        ),
    ]
