# Generated by Django 4.1.7 on 2023-05-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_alter_area_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='area.block'),
        ),
    ]
