# Generated by Django 4.1.7 on 2023-05-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0008_alter_area_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='registration_block_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='registration block id'),
        ),
    ]
