# Generated by Django 4.1.7 on 2023-06-10 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('attribution', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherqueueposition',
            name='blockk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='area.blockk'),
            preserve_default=False,
        ),
    ]
