# Generated by Django 4.1.7 on 2023-07-13 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area', '0001_initial'),
        ('attribution', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQueuePositionBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('blockk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.blockk')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
