# Generated by Django 4.1.7 on 2023-09-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_end',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_start',
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(default=1, max_length=500, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='title'),
        ),
    ]
