# Generated by Django 4.1.7 on 2023-09-04 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_deadline_semester_alter_deadline_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='semester',
            field=models.CharField(max_length=1, verbose_name='semester'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='year',
            field=models.CharField(max_length=4, verbose_name='year'),
        ),
    ]
