# Generated by Django 4.1.7 on 2023-05-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='is_high_school',
        ),
    ]
