# Generated by Django 4.1.7 on 2023-05-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='period',
            field=models.CharField(choices=[('morning', 'MORNING'), ('afternoon', 'AFTERNOON'), ('night', 'NIGHT')], max_length=45, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='class',
            name='registration_class_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='registration class id'),
        ),
    ]
