# Generated by Django 4.1.7 on 2023-05-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_remove_class_is_high_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
    ]
