# Generated by Django 4.1.7 on 2023-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='number_criteria',
            field=models.IntegerField(null=True, unique=True, verbose_name='number criteria'),
        ),
    ]
