# Generated by Django 4.1.7 on 2023-05-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadline',
            options={'verbose_name': 'deadline', 'verbose_name_plural': 'deadlines'},
        ),
        migrations.RenameField(
            model_name='deadline',
            old_name='deadline_start',
            new_name='daedline_start',
        ),
    ]
