# Generated by Django 4.1.7 on 2023-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='timeslot',
        ),
        migrations.CreateModel(
            name='Day_combo',
            fields=[
                ('day_combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY')], max_length=45, verbose_name='day')),
                ('timeslots', models.ManyToManyField(related_name='day_combos', to='timetable.timeslot')),
            ],
            options={
                'verbose_name': 'day_combo',
                'verbose_name_plural': 'day_combos',
            },
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_combo',
            field=models.ManyToManyField(related_name='day_combos', to='timetable.day_combo'),
        ),
    ]
