# Generated by Django 4.1.7 on 2023-05-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_area_is_high_school'),
        ('timetable', '0002_timetable_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='name',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='area.area'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour_end',
            field=models.TimeField(verbose_name='hour end'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='hour_start',
            field=models.TimeField(verbose_name='hour start'),
        ),
    ]
