# Generated by Django 4.1.7 on 2023-06-17 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable_user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
