# Generated by Django 4.1.7 on 2023-05-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_remove_timeslot_name_timeslot_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'timeslot', 'verbose_name_plural': 'timeslots'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'timetable', 'verbose_name_plural': 'timetables'},
        ),
        migrations.AlterModelOptions(
            name='timetable_user',
            options={'verbose_name': 'timetable_user', 'verbose_name_plural': 'timetable_users'},
        ),
    ]
