# Generated by Django 4.1.7 on 2023-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='position'),
        ),
    ]
