# Generated by Django 4.1.7 on 2023-05-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_alter_block_acronym_alter_block_name_block'),
        ('timetable', '0004_timeslot_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='area.area'),
        ),
    ]
