# Generated by Django 4.1.7 on 2023-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="course",
            name="start_time",
        ),
        migrations.AddField(
            model_name="course",
            name="end_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="start_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
